eureka:
  instance:
    hostname: eureka2
  client:
    register-with-eureka: true     #profile的配置会覆盖公用配置
    fetch-registry: true            #profile的配置会覆盖公用配置
    service-url:
      defaultZone: http://eureka1:2001/eureka   #eureka2启动时向eureka1注册
